# Generated by Django 5.0.6 on 2024-12-15 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Metal', 'Metal'), ('Wood', 'Wood'), ('Concrete', 'Concrete'), ('Plastic', 'Plastic'), ('Glass', 'Glass')], default='Metal', max_length=50)),
                ('sub_category', models.CharField(choices=[('Sheet Metal', 'Sheet Metal'), ('Cast Iron', 'Cast Iron'), ('Hardwood', 'Hardwood'), ('Plywood', 'Plywood'), ('Reinforced Concrete', 'Reinforced Concrete'), ('Thermoplastic', 'Thermoplastic'), ('Tempered Glass', 'Tempered Glass')], default='Sheet Metal', max_length=50)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
